# Generated by Django 2.1.5 on 2019-03-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=250)),
                ('base', models.CharField(max_length=100)),
                ('satellite', models.CharField(max_length=250)),
                ('targets', models.CharField(max_length=250)),
                ('money', models.IntegerField()),
                ('strikes', models.IntegerField()),
                ('strikes_recieved', models.IntegerField()),
                ('locations', models.ManyToManyField(to='main_app.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=100)),
                ('v_min', models.IntegerField()),
                ('v_max', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='weapons',
            field=models.ManyToManyField(to='main_app.Weapon'),
        ),
    ]
